### PR TITLE
Fixed deprecated functions

### PR DESCRIPTION
**Pull request by mdw771**
- Replaced deprecated functions `wavread` and `wavwrite` with `audioread` and `audiowrite`. 
- Added function `sr_convert` for conversion from 2-channel sound files with arbitrary sample rates to 16 kHz mono-channel.

### CODE REVIEW

**Review by MaigoAkisame — CHANGES_REQUESTED** [review]
Thanks for your pull request.

Replacing "wav*" with "audio*" is good.

But the sr_convert function isn't called anywhere else.
If you want the code to support audio formats other than 16kHz mono, it's better to replace the error-checking code (Lines 29~32) in vmsep.m with the following lines:
```
x = mean(resample(x, 16000, fs));
fs = 16000;
```
which performs what your sr_convert function does.

**Comment by mdw771** [comment]
Thanks for the comments. `sr_convert.m` has been removed and `vmsep.m` has been changed accordingly.

**Comment by MaigoAkisame** [comment]
I'm sorry that I missed an argument in the following line:
`x = mean(resample(x, 16000, fs));`
It should be
`x = mean(resample(x, 16000, fs), 2);`
in order to average the channels, not the samples.

Would you mind making the change so I can pull it?

**Review by MaigoAkisame — APPROVED** [review]

**Comment by MaigoAkisame** [comment]
Thank you!

**Pull request merged**
